# Generated by Django 2.1.4 on 2018-12-16 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuckoo', '0003_remove_searchinput_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='movie_star_all',
            field=models.CharField(default='No one', max_length=200),
        ),
    ]
