# Generated by Django 2.1.4 on 2018-12-17 14:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuckoo', '0004_searchresult_movie_star_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='search_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searchresult', to='cuckoo.SearchInput'),
        ),
    ]
