# Generated by Django 2.1.4 on 2018-12-17 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuckoo', '0005_auto_20181217_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='searchresult',
            name='search_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuckoo.SearchInput'),
        ),
    ]
