# Generated by Django 2.1.4 on 2018-12-23 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cuckoo', '0006_auto_20181217_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchinput',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='searchresult',
            name='favorite_msg',
            field=models.CharField(default='收藏', max_length=10),
        ),
    ]
