# Generated by Django 2.1.4 on 2018-12-23 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuckoo', '0007_auto_20181224_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchinput',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
