# Generated by Django 2.1.4 on 2018-12-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuckoo', '0010_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchresult',
            name='movie_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
