# Generated by Django 2.1.4 on 2018-12-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuckoo', '0011_searchresult_movie_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchresult',
            old_name='movie_id',
            new_name='movie_url',
        ),
        migrations.AddField(
            model_name='favorite',
            name='movie_url',
            field=models.CharField(default='', max_length=50),
        ),
    ]
